version: '3'

services:
  web:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    restart: always
    command: npm start
    depends_on:
      - db
  
  db:
    image: mongo:latest
    ports: 
      - 27017:27017