FROM node:12.7-alpine AS build
WORKDIR /tmp
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /tmp/dist/aston-villa-app /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g","daemon off;"]
