version: '3'

services:
  db:
    image: mysql:latest
    container_name: db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=db1
      - MYSQL_USER=mohamed
      - MYSQL_PASSWORD=123456
