# FROM node:14
# WORKDIR /usr/src/app
# COPY package.json .
# COPY package-lock.json .
# RUN npm install
# COPY . .
# EXPOSE 3000
# CMD ["npm","start"]

FROM node:14 as build
WORKDIR /usr/src/app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build


FROM nginx
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]